/* tslint:disable */
/* eslint-disable */
/**
 * CDP Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CustomerAddCustomerToGroupRequest,
  CustomerAddressCreateRequest,
  CustomerAddressCustomerResponse,
  CustomerAddressDeleteRequest,
  CustomerAddressDeleteResponse,
  CustomerAddressUpdateRequest,
  CustomerAddressUpdateResponse,
  CustomerBulkUpdateRequest,
  CustomerBulkUpdateResponse,
  CustomerCreateGroupRequest,
  CustomerCreateRequest,
  CustomerCreateSubscriberRequest,
  CustomerCustomerResponse,
  CustomerDeleteGroupRequest,
  CustomerDeleteGroupResponse,
  CustomerFindByEmailRequest,
  CustomerFindByIdRequest,
  CustomerFindManyRequest,
  CustomerFindManyResponse,
  CustomerFindSubscriberByEmailRequest,
  CustomerFindSubscriberByIdRequest,
  CustomerGetGroupByCodeRequest,
  CustomerGetGroupByIdRequest,
  CustomerGrantPermissionsRequest,
  CustomerGroupResponse,
  CustomerListCustomersRequest,
  CustomerListCustomersResponse,
  CustomerListGroupsRequest,
  CustomerListGroupsResponse,
  CustomerRemoveCustomerFromGroupRequest,
  CustomerRemoveDefaultAddressRequest,
  CustomerRevokePermissionsRequest,
  CustomerSearchRequest,
  CustomerSearchResponse,
  CustomerSetDefaultAddressRequest,
  CustomerSetPermissionsRequest,
  CustomerSubscriberResponse,
  CustomerUnsubscribeRequest,
  CustomerUnsubscribeResponse,
  CustomerUpdateGroupRequest,
  CustomerUpdateRequest,
  CustomerUpdateSubscriberRequest,
  GooglerpcStatus,
} from '../models/index';
import {
    CustomerAddCustomerToGroupRequestFromJSON,
    CustomerAddCustomerToGroupRequestToJSON,
    CustomerAddressCreateRequestFromJSON,
    CustomerAddressCreateRequestToJSON,
    CustomerAddressCustomerResponseFromJSON,
    CustomerAddressCustomerResponseToJSON,
    CustomerAddressDeleteRequestFromJSON,
    CustomerAddressDeleteRequestToJSON,
    CustomerAddressDeleteResponseFromJSON,
    CustomerAddressDeleteResponseToJSON,
    CustomerAddressUpdateRequestFromJSON,
    CustomerAddressUpdateRequestToJSON,
    CustomerAddressUpdateResponseFromJSON,
    CustomerAddressUpdateResponseToJSON,
    CustomerBulkUpdateRequestFromJSON,
    CustomerBulkUpdateRequestToJSON,
    CustomerBulkUpdateResponseFromJSON,
    CustomerBulkUpdateResponseToJSON,
    CustomerCreateGroupRequestFromJSON,
    CustomerCreateGroupRequestToJSON,
    CustomerCreateRequestFromJSON,
    CustomerCreateRequestToJSON,
    CustomerCreateSubscriberRequestFromJSON,
    CustomerCreateSubscriberRequestToJSON,
    CustomerCustomerResponseFromJSON,
    CustomerCustomerResponseToJSON,
    CustomerDeleteGroupRequestFromJSON,
    CustomerDeleteGroupRequestToJSON,
    CustomerDeleteGroupResponseFromJSON,
    CustomerDeleteGroupResponseToJSON,
    CustomerFindByEmailRequestFromJSON,
    CustomerFindByEmailRequestToJSON,
    CustomerFindByIdRequestFromJSON,
    CustomerFindByIdRequestToJSON,
    CustomerFindManyRequestFromJSON,
    CustomerFindManyRequestToJSON,
    CustomerFindManyResponseFromJSON,
    CustomerFindManyResponseToJSON,
    CustomerFindSubscriberByEmailRequestFromJSON,
    CustomerFindSubscriberByEmailRequestToJSON,
    CustomerFindSubscriberByIdRequestFromJSON,
    CustomerFindSubscriberByIdRequestToJSON,
    CustomerGetGroupByCodeRequestFromJSON,
    CustomerGetGroupByCodeRequestToJSON,
    CustomerGetGroupByIdRequestFromJSON,
    CustomerGetGroupByIdRequestToJSON,
    CustomerGrantPermissionsRequestFromJSON,
    CustomerGrantPermissionsRequestToJSON,
    CustomerGroupResponseFromJSON,
    CustomerGroupResponseToJSON,
    CustomerListCustomersRequestFromJSON,
    CustomerListCustomersRequestToJSON,
    CustomerListCustomersResponseFromJSON,
    CustomerListCustomersResponseToJSON,
    CustomerListGroupsRequestFromJSON,
    CustomerListGroupsRequestToJSON,
    CustomerListGroupsResponseFromJSON,
    CustomerListGroupsResponseToJSON,
    CustomerRemoveCustomerFromGroupRequestFromJSON,
    CustomerRemoveCustomerFromGroupRequestToJSON,
    CustomerRemoveDefaultAddressRequestFromJSON,
    CustomerRemoveDefaultAddressRequestToJSON,
    CustomerRevokePermissionsRequestFromJSON,
    CustomerRevokePermissionsRequestToJSON,
    CustomerSearchRequestFromJSON,
    CustomerSearchRequestToJSON,
    CustomerSearchResponseFromJSON,
    CustomerSearchResponseToJSON,
    CustomerSetDefaultAddressRequestFromJSON,
    CustomerSetDefaultAddressRequestToJSON,
    CustomerSetPermissionsRequestFromJSON,
    CustomerSetPermissionsRequestToJSON,
    CustomerSubscriberResponseFromJSON,
    CustomerSubscriberResponseToJSON,
    CustomerUnsubscribeRequestFromJSON,
    CustomerUnsubscribeRequestToJSON,
    CustomerUnsubscribeResponseFromJSON,
    CustomerUnsubscribeResponseToJSON,
    CustomerUpdateGroupRequestFromJSON,
    CustomerUpdateGroupRequestToJSON,
    CustomerUpdateRequestFromJSON,
    CustomerUpdateRequestToJSON,
    CustomerUpdateSubscriberRequestFromJSON,
    CustomerUpdateSubscriberRequestToJSON,
    GooglerpcStatusFromJSON,
    GooglerpcStatusToJSON,
} from '../models/index';

export interface CustomerAcquireSubscriberRequest {
    body: CustomerCreateSubscriberRequest;
}

export interface CustomerAcquireUnsubscriberRequest {
    body: CustomerUnsubscribeRequest;
}

export interface CustomerAddCustomerToGroupOperationRequest {
    body: CustomerAddCustomerToGroupRequest;
}

export interface CustomerBulkUpdateOperationRequest {
    body: CustomerBulkUpdateRequest;
}

export interface CustomerCreateOperationRequest {
    body: CustomerCreateRequest;
}

export interface CustomerCreateAddressRequest {
    body: CustomerAddressCreateRequest;
}

export interface CustomerCreateGroupOperationRequest {
    body: CustomerCreateGroupRequest;
}

export interface CustomerCreateSubscriberOperationRequest {
    body: CustomerCreateSubscriberRequest;
}

export interface CustomerDeleteAddressRequest {
    body: CustomerAddressDeleteRequest;
}

export interface CustomerDeleteGroupOperationRequest {
    body: CustomerDeleteGroupRequest;
}

export interface CustomerFindRequest {
    body: CustomerFindManyRequest;
}

export interface CustomerFindByEmailOperationRequest {
    body: CustomerFindByEmailRequest;
}

export interface CustomerFindByIdOperationRequest {
    body: CustomerFindByIdRequest;
}

export interface CustomerFindSubscriberByEmailOperationRequest {
    body: CustomerFindSubscriberByEmailRequest;
}

export interface CustomerFindSubscriberByIdOperationRequest {
    body: CustomerFindSubscriberByIdRequest;
}

export interface CustomerGetGroupByCodeOperationRequest {
    body: CustomerGetGroupByCodeRequest;
}

export interface CustomerGetGroupByIdOperationRequest {
    body: CustomerGetGroupByIdRequest;
}

export interface CustomerGrantPermissionsOperationRequest {
    body: CustomerGrantPermissionsRequest;
}

export interface CustomerListCustomersOperationRequest {
    body: CustomerListCustomersRequest;
}

export interface CustomerListGroupsOperationRequest {
    body: CustomerListGroupsRequest;
}

export interface CustomerRemoveCustomerFromGroupOperationRequest {
    body: CustomerRemoveCustomerFromGroupRequest;
}

export interface CustomerRemoveDefaultAddressOperationRequest {
    body: CustomerRemoveDefaultAddressRequest;
}

export interface CustomerRevokePermissionsOperationRequest {
    body: CustomerRevokePermissionsRequest;
}

export interface CustomerSearchOperationRequest {
    body: CustomerSearchRequest;
}

export interface CustomerSetDefaultAddressOperationRequest {
    body: CustomerSetDefaultAddressRequest;
}

export interface CustomerSetPermissionsOperationRequest {
    body: CustomerSetPermissionsRequest;
}

export interface CustomerUnsubscribeOperationRequest {
    body: CustomerUnsubscribeRequest;
}

export interface CustomerUpdateOperationRequest {
    body: CustomerUpdateRequest;
}

export interface CustomerUpdateAddressRequest {
    body: CustomerAddressUpdateRequest;
}

export interface CustomerUpdateGroupOperationRequest {
    body: CustomerUpdateGroupRequest;
}

export interface CustomerUpdateSubscriberOperationRequest {
    body: CustomerUpdateSubscriberRequest;
}

/**
 * 
 */
export class CustomerApi extends runtime.BaseAPI {

    /**
     */
    async customerAcquireSubscriberRaw(requestParameters: CustomerAcquireSubscriberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomerSubscriberResponse>> {
        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling customerAcquireSubscriber.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/customer.Customer/AcquireSubscriber`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CustomerCreateSubscriberRequestToJSON(requestParameters.body),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomerSubscriberResponseFromJSON(jsonValue));
    }

    /**
     */
    async customerAcquireSubscriber(requestParameters: CustomerAcquireSubscriberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomerSubscriberResponse> {
        const response = await this.customerAcquireSubscriberRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async customerAcquireUnsubscriberRaw(requestParameters: CustomerAcquireUnsubscriberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomerUnsubscribeResponse>> {
        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling customerAcquireUnsubscriber.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/customer.Customer/AcquireUnsubscriber`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CustomerUnsubscribeRequestToJSON(requestParameters.body),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomerUnsubscribeResponseFromJSON(jsonValue));
    }

    /**
     */
    async customerAcquireUnsubscriber(requestParameters: CustomerAcquireUnsubscriberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomerUnsubscribeResponse> {
        const response = await this.customerAcquireUnsubscriberRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async customerAddCustomerToGroupRaw(requestParameters: CustomerAddCustomerToGroupOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomerGroupResponse>> {
        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling customerAddCustomerToGroup.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/customer.Customer/AddCustomerToGroup`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CustomerAddCustomerToGroupRequestToJSON(requestParameters.body),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomerGroupResponseFromJSON(jsonValue));
    }

    /**
     */
    async customerAddCustomerToGroup(requestParameters: CustomerAddCustomerToGroupOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomerGroupResponse> {
        const response = await this.customerAddCustomerToGroupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async customerBulkUpdateRaw(requestParameters: CustomerBulkUpdateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomerBulkUpdateResponse>> {
        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling customerBulkUpdate.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/customer.Customer/BulkUpdate`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CustomerBulkUpdateRequestToJSON(requestParameters.body),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomerBulkUpdateResponseFromJSON(jsonValue));
    }

    /**
     */
    async customerBulkUpdate(requestParameters: CustomerBulkUpdateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomerBulkUpdateResponse> {
        const response = await this.customerBulkUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async customerCreateRaw(requestParameters: CustomerCreateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomerCustomerResponse>> {
        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling customerCreate.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/customer.Customer/Create`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CustomerCreateRequestToJSON(requestParameters.body),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomerCustomerResponseFromJSON(jsonValue));
    }

    /**
     */
    async customerCreate(requestParameters: CustomerCreateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomerCustomerResponse> {
        const response = await this.customerCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async customerCreateAddressRaw(requestParameters: CustomerCreateAddressRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomerAddressCustomerResponse>> {
        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling customerCreateAddress.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/customer.Customer/CreateAddress`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CustomerAddressCreateRequestToJSON(requestParameters.body),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomerAddressCustomerResponseFromJSON(jsonValue));
    }

    /**
     */
    async customerCreateAddress(requestParameters: CustomerCreateAddressRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomerAddressCustomerResponse> {
        const response = await this.customerCreateAddressRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async customerCreateGroupRaw(requestParameters: CustomerCreateGroupOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomerGroupResponse>> {
        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling customerCreateGroup.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/customer.Customer/CreateGroup`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CustomerCreateGroupRequestToJSON(requestParameters.body),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomerGroupResponseFromJSON(jsonValue));
    }

    /**
     */
    async customerCreateGroup(requestParameters: CustomerCreateGroupOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomerGroupResponse> {
        const response = await this.customerCreateGroupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async customerCreateSubscriberRaw(requestParameters: CustomerCreateSubscriberOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomerSubscriberResponse>> {
        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling customerCreateSubscriber.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/customer.Customer/CreateSubscriber`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CustomerCreateSubscriberRequestToJSON(requestParameters.body),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomerSubscriberResponseFromJSON(jsonValue));
    }

    /**
     */
    async customerCreateSubscriber(requestParameters: CustomerCreateSubscriberOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomerSubscriberResponse> {
        const response = await this.customerCreateSubscriberRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async customerDeleteAddressRaw(requestParameters: CustomerDeleteAddressRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomerAddressDeleteResponse>> {
        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling customerDeleteAddress.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/customer.Customer/DeleteAddress`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CustomerAddressDeleteRequestToJSON(requestParameters.body),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomerAddressDeleteResponseFromJSON(jsonValue));
    }

    /**
     */
    async customerDeleteAddress(requestParameters: CustomerDeleteAddressRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomerAddressDeleteResponse> {
        const response = await this.customerDeleteAddressRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async customerDeleteGroupRaw(requestParameters: CustomerDeleteGroupOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomerDeleteGroupResponse>> {
        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling customerDeleteGroup.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/customer.Customer/DeleteGroup`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CustomerDeleteGroupRequestToJSON(requestParameters.body),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomerDeleteGroupResponseFromJSON(jsonValue));
    }

    /**
     */
    async customerDeleteGroup(requestParameters: CustomerDeleteGroupOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomerDeleteGroupResponse> {
        const response = await this.customerDeleteGroupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async customerFindRaw(requestParameters: CustomerFindRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomerFindManyResponse>> {
        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling customerFind.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/customer.Customer/Find`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CustomerFindManyRequestToJSON(requestParameters.body),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomerFindManyResponseFromJSON(jsonValue));
    }

    /**
     */
    async customerFind(requestParameters: CustomerFindRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomerFindManyResponse> {
        const response = await this.customerFindRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async customerFindByEmailRaw(requestParameters: CustomerFindByEmailOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomerCustomerResponse>> {
        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling customerFindByEmail.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/customer.Customer/FindByEmail`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CustomerFindByEmailRequestToJSON(requestParameters.body),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomerCustomerResponseFromJSON(jsonValue));
    }

    /**
     */
    async customerFindByEmail(requestParameters: CustomerFindByEmailOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomerCustomerResponse> {
        const response = await this.customerFindByEmailRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async customerFindByIdRaw(requestParameters: CustomerFindByIdOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomerCustomerResponse>> {
        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling customerFindById.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/customer.Customer/FindById`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CustomerFindByIdRequestToJSON(requestParameters.body),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomerCustomerResponseFromJSON(jsonValue));
    }

    /**
     */
    async customerFindById(requestParameters: CustomerFindByIdOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomerCustomerResponse> {
        const response = await this.customerFindByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async customerFindSubscriberByEmailRaw(requestParameters: CustomerFindSubscriberByEmailOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomerSubscriberResponse>> {
        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling customerFindSubscriberByEmail.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/customer.Customer/FindSubscriberByEmail`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CustomerFindSubscriberByEmailRequestToJSON(requestParameters.body),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomerSubscriberResponseFromJSON(jsonValue));
    }

    /**
     */
    async customerFindSubscriberByEmail(requestParameters: CustomerFindSubscriberByEmailOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomerSubscriberResponse> {
        const response = await this.customerFindSubscriberByEmailRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async customerFindSubscriberByIdRaw(requestParameters: CustomerFindSubscriberByIdOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomerSubscriberResponse>> {
        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling customerFindSubscriberById.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/customer.Customer/FindSubscriberById`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CustomerFindSubscriberByIdRequestToJSON(requestParameters.body),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomerSubscriberResponseFromJSON(jsonValue));
    }

    /**
     */
    async customerFindSubscriberById(requestParameters: CustomerFindSubscriberByIdOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomerSubscriberResponse> {
        const response = await this.customerFindSubscriberByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async customerGetGroupByCodeRaw(requestParameters: CustomerGetGroupByCodeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomerGroupResponse>> {
        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling customerGetGroupByCode.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/customer.Customer/GetGroupByCode`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CustomerGetGroupByCodeRequestToJSON(requestParameters.body),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomerGroupResponseFromJSON(jsonValue));
    }

    /**
     */
    async customerGetGroupByCode(requestParameters: CustomerGetGroupByCodeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomerGroupResponse> {
        const response = await this.customerGetGroupByCodeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async customerGetGroupByIdRaw(requestParameters: CustomerGetGroupByIdOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomerGroupResponse>> {
        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling customerGetGroupById.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/customer.Customer/GetGroupById`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CustomerGetGroupByIdRequestToJSON(requestParameters.body),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomerGroupResponseFromJSON(jsonValue));
    }

    /**
     */
    async customerGetGroupById(requestParameters: CustomerGetGroupByIdOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomerGroupResponse> {
        const response = await this.customerGetGroupByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * GrantPermissions add permissions to a customer
     */
    async customerGrantPermissionsRaw(requestParameters: CustomerGrantPermissionsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling customerGrantPermissions.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/customer.Customer/GrantPermissions`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CustomerGrantPermissionsRequestToJSON(requestParameters.body),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * GrantPermissions add permissions to a customer
     */
    async customerGrantPermissions(requestParameters: CustomerGrantPermissionsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.customerGrantPermissionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async customerListCustomersRaw(requestParameters: CustomerListCustomersOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomerListCustomersResponse>> {
        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling customerListCustomers.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/customer.Customer/ListCustomers`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CustomerListCustomersRequestToJSON(requestParameters.body),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomerListCustomersResponseFromJSON(jsonValue));
    }

    /**
     */
    async customerListCustomers(requestParameters: CustomerListCustomersOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomerListCustomersResponse> {
        const response = await this.customerListCustomersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async customerListGroupsRaw(requestParameters: CustomerListGroupsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomerListGroupsResponse>> {
        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling customerListGroups.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/customer.Customer/ListGroups`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CustomerListGroupsRequestToJSON(requestParameters.body),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomerListGroupsResponseFromJSON(jsonValue));
    }

    /**
     */
    async customerListGroups(requestParameters: CustomerListGroupsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomerListGroupsResponse> {
        const response = await this.customerListGroupsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async customerRemoveCustomerFromGroupRaw(requestParameters: CustomerRemoveCustomerFromGroupOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomerGroupResponse>> {
        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling customerRemoveCustomerFromGroup.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/customer.Customer/RemoveCustomerFromGroup`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CustomerRemoveCustomerFromGroupRequestToJSON(requestParameters.body),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomerGroupResponseFromJSON(jsonValue));
    }

    /**
     */
    async customerRemoveCustomerFromGroup(requestParameters: CustomerRemoveCustomerFromGroupOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomerGroupResponse> {
        const response = await this.customerRemoveCustomerFromGroupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async customerRemoveDefaultAddressRaw(requestParameters: CustomerRemoveDefaultAddressOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomerCustomerResponse>> {
        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling customerRemoveDefaultAddress.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/customer.Customer/RemoveDefaultAddress`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CustomerRemoveDefaultAddressRequestToJSON(requestParameters.body),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomerCustomerResponseFromJSON(jsonValue));
    }

    /**
     */
    async customerRemoveDefaultAddress(requestParameters: CustomerRemoveDefaultAddressOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomerCustomerResponse> {
        const response = await this.customerRemoveDefaultAddressRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * RevokePermissions remove permissions from a customer
     */
    async customerRevokePermissionsRaw(requestParameters: CustomerRevokePermissionsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling customerRevokePermissions.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/customer.Customer/RevokePermissions`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CustomerRevokePermissionsRequestToJSON(requestParameters.body),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * RevokePermissions remove permissions from a customer
     */
    async customerRevokePermissions(requestParameters: CustomerRevokePermissionsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.customerRevokePermissionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async customerSearchRaw(requestParameters: CustomerSearchOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomerSearchResponse>> {
        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling customerSearch.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/customer.Customer/Search`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CustomerSearchRequestToJSON(requestParameters.body),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomerSearchResponseFromJSON(jsonValue));
    }

    /**
     */
    async customerSearch(requestParameters: CustomerSearchOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomerSearchResponse> {
        const response = await this.customerSearchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async customerSetDefaultAddressRaw(requestParameters: CustomerSetDefaultAddressOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomerCustomerResponse>> {
        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling customerSetDefaultAddress.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/customer.Customer/SetDefaultAddress`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CustomerSetDefaultAddressRequestToJSON(requestParameters.body),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomerCustomerResponseFromJSON(jsonValue));
    }

    /**
     */
    async customerSetDefaultAddress(requestParameters: CustomerSetDefaultAddressOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomerCustomerResponse> {
        const response = await this.customerSetDefaultAddressRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * SetPermissions set permissions to a customer
     */
    async customerSetPermissionsRaw(requestParameters: CustomerSetPermissionsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling customerSetPermissions.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/customer.Customer/SetPermissions`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CustomerSetPermissionsRequestToJSON(requestParameters.body),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * SetPermissions set permissions to a customer
     */
    async customerSetPermissions(requestParameters: CustomerSetPermissionsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.customerSetPermissionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async customerUnsubscribeRaw(requestParameters: CustomerUnsubscribeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomerUnsubscribeResponse>> {
        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling customerUnsubscribe.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/customer.Customer/Unsubscribe`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CustomerUnsubscribeRequestToJSON(requestParameters.body),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomerUnsubscribeResponseFromJSON(jsonValue));
    }

    /**
     */
    async customerUnsubscribe(requestParameters: CustomerUnsubscribeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomerUnsubscribeResponse> {
        const response = await this.customerUnsubscribeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async customerUpdateRaw(requestParameters: CustomerUpdateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomerCustomerResponse>> {
        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling customerUpdate.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/customer.Customer/Update`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CustomerUpdateRequestToJSON(requestParameters.body),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomerCustomerResponseFromJSON(jsonValue));
    }

    /**
     */
    async customerUpdate(requestParameters: CustomerUpdateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomerCustomerResponse> {
        const response = await this.customerUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async customerUpdateAddressRaw(requestParameters: CustomerUpdateAddressRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomerAddressUpdateResponse>> {
        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling customerUpdateAddress.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/customer.Customer/UpdateAddress`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CustomerAddressUpdateRequestToJSON(requestParameters.body),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomerAddressUpdateResponseFromJSON(jsonValue));
    }

    /**
     */
    async customerUpdateAddress(requestParameters: CustomerUpdateAddressRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomerAddressUpdateResponse> {
        const response = await this.customerUpdateAddressRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async customerUpdateGroupRaw(requestParameters: CustomerUpdateGroupOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomerGroupResponse>> {
        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling customerUpdateGroup.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/customer.Customer/UpdateGroup`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CustomerUpdateGroupRequestToJSON(requestParameters.body),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomerGroupResponseFromJSON(jsonValue));
    }

    /**
     */
    async customerUpdateGroup(requestParameters: CustomerUpdateGroupOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomerGroupResponse> {
        const response = await this.customerUpdateGroupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async customerUpdateSubscriberRaw(requestParameters: CustomerUpdateSubscriberOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomerSubscriberResponse>> {
        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling customerUpdateSubscriber.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/customer.Customer/UpdateSubscriber`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CustomerUpdateSubscriberRequestToJSON(requestParameters.body),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomerSubscriberResponseFromJSON(jsonValue));
    }

    /**
     */
    async customerUpdateSubscriber(requestParameters: CustomerUpdateSubscriberOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomerSubscriberResponse> {
        const response = await this.customerUpdateSubscriberRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
