/* tslint:disable */
/* eslint-disable */
/**
 * CDP Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const BulkUpdateRequestAction = {
    Enable: 'ENABLE',
    Disable: 'DISABLE',
    Delete: 'DELETE'
} as const;
export type BulkUpdateRequestAction = typeof BulkUpdateRequestAction[keyof typeof BulkUpdateRequestAction];


export function BulkUpdateRequestActionFromJSON(json: any): BulkUpdateRequestAction {
    return BulkUpdateRequestActionFromJSONTyped(json, false);
}

export function BulkUpdateRequestActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): BulkUpdateRequestAction {
    return json as BulkUpdateRequestAction;
}

export function BulkUpdateRequestActionToJSON(value?: BulkUpdateRequestAction | null): any {
    return value as any;
}

