/* tslint:disable */
/* eslint-disable */
/**
 * CDP Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface CustomerSubscriberResponseWithNewsletterRequest
 */
export interface CustomerSubscriberResponseWithNewsletterRequest {
    /**
     * 
     * @type {string}
     * @memberof CustomerSubscriberResponseWithNewsletterRequest
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerSubscriberResponseWithNewsletterRequest
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerSubscriberResponseWithNewsletterRequest
     */
    'lastname'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerSubscriberResponseWithNewsletterRequest
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerSubscriberResponseWithNewsletterRequest
     */
    'country'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerSubscriberResponseWithNewsletterRequest
     */
    'gender'?: string;
    /**
     * 
     * @type {Date}
     * @memberof CustomerSubscriberResponseWithNewsletterRequest
     */
    'birthdate'?: Date;
    /**
     * 
     * @type {string}
     * @memberof CustomerSubscriberResponseWithNewsletterRequest
     */
    'nationality'?: string;
    /**
     * 
     * @type {CustomerEMFields}
     * @memberof CustomerSubscriberResponseWithNewsletterRequest
     */
    'em'?: CustomerEMFields;
    /**
     * 
     * @type {string}
     * @memberof CustomerSubscriberResponseWithNewsletterRequest
     */
    'preferredLocale'?: string;
    /**
     * 
     * @type {Date}
     * @memberof CustomerSubscriberResponseWithNewsletterRequest
     */
    'createdAt'?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CustomerSubscriberResponseWithNewsletterRequest
     */
    'updatedAt'?: Date;
    /**
     * 
     * @type {Array<CustomerNewsletterRequest>}
     * @memberof CustomerSubscriberResponseWithNewsletterRequest
     */
    'newsletters'?: Array<CustomerNewsletterRequest>;
}
