/* tslint:disable */
/* eslint-disable */
/**
 * CDP Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface CustomerSubscriberResponse
 */
export interface CustomerSubscriberResponse {
    /**
     * 
     * @type {string}
     * @memberof CustomerSubscriberResponse
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerSubscriberResponse
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerSubscriberResponse
     */
    'lastname'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerSubscriberResponse
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerSubscriberResponse
     */
    'country'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerSubscriberResponse
     */
    'gender'?: string;
    /**
     * 
     * @type {Date}
     * @memberof CustomerSubscriberResponse
     */
    'birthdate'?: Date;
    /**
     * 
     * @type {string}
     * @memberof CustomerSubscriberResponse
     */
    'nationality'?: string;
    /**
     * 
     * @type {CustomerEMFields}
     * @memberof CustomerSubscriberResponse
     */
    'em'?: CustomerEMFields;
    /**
     * 
     * @type {Date}
     * @memberof CustomerSubscriberResponse
     */
    'createdAt'?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CustomerSubscriberResponse
     */
    'updatedAt'?: Date;
    /**
     * 
     * @type {Array<CustomerNewsletterResponse>}
     * @memberof CustomerSubscriberResponse
     */
    'newsletters'?: Array<CustomerNewsletterResponse>;
    /**
     * 
     * @type {string}
     * @memberof CustomerSubscriberResponse
     */
    'market'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerSubscriberResponse
     */
    'preferredLocale'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CustomerSubscriberResponse
     */
    'customerGroups'?: Array<string>;
}
