/* tslint:disable */
/* eslint-disable */
/**
 * CDP Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const CustomerPermission = {
    Unknown: 'PERMISSION_UNKNOWN',
    Login: 'PERMISSION_LOGIN',
    Buy: 'PERMISSION_BUY'
} as const;
export type CustomerPermission = typeof CustomerPermission[keyof typeof CustomerPermission];


export function CustomerPermissionFromJSON(json: any): CustomerPermission {
    return CustomerPermissionFromJSONTyped(json, false);
}

export function CustomerPermissionFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerPermission {
    return json as CustomerPermission;
}

export function CustomerPermissionToJSON(value?: CustomerPermission | null): any {
    return value as any;
}

