/* tslint:disable */
/* eslint-disable */
/**
 * CDP Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface CustomerNewsletterRequest
 */
export interface CustomerNewsletterRequest {
    /**
     * 
     * @type {string}
     * @memberof CustomerNewsletterRequest
     */
    'newsletterGrn'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerNewsletterRequest
     */
    'name'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CustomerNewsletterRequest
     */
    'subscribed'?: boolean;
}
