/* tslint:disable */
/* eslint-disable */
/**
 * CDP Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface CustomerConsent
 */
export interface CustomerConsent {
    /**
     * 
     * @type {string}
     * @memberof CustomerConsent
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerConsent
     */
    'grn'?: string;
    /**
     * 
     * @type {{ [key: string]: boolean; }}
     * @memberof CustomerConsent
     */
    'preferences'?: { [key: string]: boolean; };
    /**
     * 
     * @type {Date}
     * @memberof CustomerConsent
     */
    'createdAt'?: Date;
    /**
     * 
     * @type {CustomerConsentSource}
     * @memberof CustomerConsent
     */
    'source'?: CustomerConsentSource;
    /**
     * 
     * @type {string}
     * @memberof CustomerConsent
     */
    'author'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerConsent
     */
    'subjectId'?: string;
}
