/* tslint:disable */
/* eslint-disable */
/**
 * CDP Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface CustomerAddressCustomerResponse
 */
export interface CustomerAddressCustomerResponse {
    /**
     * 
     * @type {CustomerEMFields}
     * @memberof CustomerAddressCustomerResponse
     */
    'em'?: CustomerEMFields;
    /**
     * 
     * @type {string}
     * @memberof CustomerAddressCustomerResponse
     */
    'grn'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerAddressCustomerResponse
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerAddressCustomerResponse
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerAddressCustomerResponse
     */
    'surname'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerAddressCustomerResponse
     */
    'street'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerAddressCustomerResponse
     */
    'number'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerAddressCustomerResponse
     */
    'zip'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerAddressCustomerResponse
     */
    'city'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerAddressCustomerResponse
     */
    'province'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerAddressCustomerResponse
     */
    'phoneNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerAddressCustomerResponse
     */
    'fiscalCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerAddressCustomerResponse
     */
    'vatNumber'?: string;
    /**
     * 
     * @type {CustomerAddressCustomerResponseKind}
     * @memberof CustomerAddressCustomerResponse
     */
    'kind'?: CustomerAddressCustomerResponseKind;
    /**
     * 
     * @type {boolean}
     * @memberof CustomerAddressCustomerResponse
     */
    'default'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CustomerAddressCustomerResponse
     */
    'country'?: string;
    /**
     * 
     * @type {Date}
     * @memberof CustomerAddressCustomerResponse
     */
    'createdAt'?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CustomerAddressCustomerResponse
     */
    'updatedAt'?: Date;
    /**
     * 
     * @type {{ [key: string]: ProtobufAny; }}
     * @memberof CustomerAddressCustomerResponse
     */
    'attributes'?: { [key: string]: ProtobufAny; };
}
