/* tslint:disable */
/* eslint-disable */
/**
 * CDP Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface CustomerListConsentsRequest
 */
export interface CustomerListConsentsRequest {
    /**
     * 
     * @type {string}
     * @memberof CustomerListConsentsRequest
     */
    'tenantId'?: string;
    /**
     * 
     * @type {number}
     * @memberof CustomerListConsentsRequest
     */
    'pageSize'?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomerListConsentsRequest
     */
    'pageToken'?: string;
    /**
     * 
     * @type {Array<ListConsentsRequestSort>}
     * @memberof CustomerListConsentsRequest
     */
    'sorts'?: Array<ListConsentsRequestSort>;
    /**
     * 
     * @type {string}
     * @memberof CustomerListConsentsRequest
     */
    'filtersMask'?: string;
    /**
     * 
     * @type {ListConsentsRequestFilters}
     * @memberof CustomerListConsentsRequest
     */
    'filters'?: ListConsentsRequestFilters;
}
