/* tslint:disable */
/* eslint-disable */
/**
 * CDP Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface CustomerPassword
 */
export interface CustomerPassword {
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof CustomerPassword
     */
    'data'?: { [key: string]: string; };
    /**
     * 
     * @type {boolean}
     * @memberof CustomerPassword
     */
    'enabled'?: boolean;
    /**
     * 
     * @type {PasswordPasswordType}
     * @memberof CustomerPassword
     */
    'type'?: PasswordPasswordType;
}
