/* tslint:disable */
/* eslint-disable */
/**
 * CDP Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface CustomerUpdateRequestPayload
 */
export interface CustomerUpdateRequestPayload {
    /**
     * 
     * @type {CustomerEMFields}
     * @memberof CustomerUpdateRequestPayload
     */
    'em'?: CustomerEMFields;
    /**
     * 
     * @type {string}
     * @memberof CustomerUpdateRequestPayload
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerUpdateRequestPayload
     */
    'surname'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerUpdateRequestPayload
     */
    'email'?: string;
    /**
     * 
     * @type {Date}
     * @memberof CustomerUpdateRequestPayload
     */
    'birthdate'?: Date;
    /**
     * 
     * @type {string}
     * @memberof CustomerUpdateRequestPayload
     */
    'gender'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CustomerUpdateRequestPayload
     */
    'enabled'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CustomerUpdateRequestPayload
     */
    'source'?: string;
    /**
     * 
     * @type {Array<CustomerAddressEntity>}
     * @memberof CustomerUpdateRequestPayload
     */
    'addresses'?: Array<CustomerAddressEntity>;
    /**
     * 
     * @type {string}
     * @memberof CustomerUpdateRequestPayload
     */
    'defaultBillingAddressId'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerUpdateRequestPayload
     */
    'defaultShippingAddressId'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerUpdateRequestPayload
     */
    'phoneNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerUpdateRequestPayload
     */
    'nationality'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CustomerUpdateRequestPayload
     */
    'groups'?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof CustomerUpdateRequestPayload
     */
    'deleted'?: boolean;
    /**
     * 
     * @type {Array<CustomerNewsletterRequest>}
     * @memberof CustomerUpdateRequestPayload
     */
    'newsletters'?: Array<CustomerNewsletterRequest>;
    /**
     * 
     * @type {{ [key: string]: ProtobufAny; }}
     * @memberof CustomerUpdateRequestPayload
     */
    'attributes'?: { [key: string]: ProtobufAny; };
    /**
     * 
     * @type {CustomerPassword}
     * @memberof CustomerUpdateRequestPayload
     */
    'migratedPassword'?: CustomerPassword;
    /**
     * 
     * @type {string}
     * @memberof CustomerUpdateRequestPayload
     */
    'preferredLocale'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerUpdateRequestPayload
     */
    'taxCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerUpdateRequestPayload
     */
    'certifiedEmail'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerUpdateRequestPayload
     */
    'market'?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof CustomerUpdateRequestPayload
     */
    'externalIds'?: { [key: string]: string; };
}
