/* tslint:disable */
/* eslint-disable */
/**
 * CDP Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const CustomerAddressCreateRequestKind = {
    Shipping: 'SHIPPING',
    Billing: 'BILLING',
    Both: 'BOTH'
} as const;
export type CustomerAddressCreateRequestKind = typeof CustomerAddressCreateRequestKind[keyof typeof CustomerAddressCreateRequestKind];


export function CustomerAddressCreateRequestKindFromJSON(json: any): CustomerAddressCreateRequestKind {
    return CustomerAddressCreateRequestKindFromJSONTyped(json, false);
}

export function CustomerAddressCreateRequestKindFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerAddressCreateRequestKind {
    return json as CustomerAddressCreateRequestKind;
}

export function CustomerAddressCreateRequestKindToJSON(value?: CustomerAddressCreateRequestKind | null): any {
    return value as any;
}

