/* tslint:disable */
/* eslint-disable */
/**
 * CDP Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const CustomerAddressEntityKind = {
    Shipping: 'SHIPPING',
    Billing: 'BILLING',
    Both: 'BOTH'
} as const;
export type CustomerAddressEntityKind = typeof CustomerAddressEntityKind[keyof typeof CustomerAddressEntityKind];


export function CustomerAddressEntityKindFromJSON(json: any): CustomerAddressEntityKind {
    return CustomerAddressEntityKindFromJSONTyped(json, false);
}

export function CustomerAddressEntityKindFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerAddressEntityKind {
    return json as CustomerAddressEntityKind;
}

export function CustomerAddressEntityKindToJSON(value?: CustomerAddressEntityKind | null): any {
    return value as any;
}

