/* tslint:disable */
/* eslint-disable */
/**
 * CDP Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface CustomerGroupResponse
 */
export interface CustomerGroupResponse {
    /**
     * 
     * @type {string}
     * @memberof CustomerGroupResponse
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerGroupResponse
     */
    'name'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CustomerGroupResponse
     */
    'customerIds'?: Array<string>;
    /**
     * 
     * @type {Date}
     * @memberof CustomerGroupResponse
     */
    'createdAt'?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CustomerGroupResponse
     */
    'updatedAt'?: Date;
    /**
     * 
     * @type {string}
     * @memberof CustomerGroupResponse
     */
    'grn'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerGroupResponse
     */
    'code'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerGroupResponse
     */
    'customerCount'?: string;
}
