/* tslint:disable */
/* eslint-disable */
/**
 * CDP Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const CustomerAddressCustomerResponseKind = {
    Shipping: 'SHIPPING',
    Billing: 'BILLING',
    Both: 'BOTH'
} as const;
export type CustomerAddressCustomerResponseKind = typeof CustomerAddressCustomerResponseKind[keyof typeof CustomerAddressCustomerResponseKind];


export function CustomerAddressCustomerResponseKindFromJSON(json: any): CustomerAddressCustomerResponseKind {
    return CustomerAddressCustomerResponseKindFromJSONTyped(json, false);
}

export function CustomerAddressCustomerResponseKindFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerAddressCustomerResponseKind {
    return json as CustomerAddressCustomerResponseKind;
}

export function CustomerAddressCustomerResponseKindToJSON(value?: CustomerAddressCustomerResponseKind | null): any {
    return value as any;
}

