/* tslint:disable */
/* eslint-disable */
/**
 * CDP Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const SortSortOrder = {
    Desc: 'DESC',
    Asc: 'ASC'
} as const;
export type SortSortOrder = typeof SortSortOrder[keyof typeof SortSortOrder];


export function SortSortOrderFromJSON(json: any): SortSortOrder {
    return SortSortOrderFromJSONTyped(json, false);
}

export function SortSortOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): SortSortOrder {
    return json as SortSortOrder;
}

export function SortSortOrderToJSON(value?: SortSortOrder | null): any {
    return value as any;
}

