/* tslint:disable */
/* eslint-disable */
/**
 * CDP Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const SortSortField = {
    Unknown: 'UNKNOWN',
    Date: 'DATE'
} as const;
export type SortSortField = typeof SortSortField[keyof typeof SortSortField];


export function SortSortFieldFromJSON(json: any): SortSortField {
    return SortSortFieldFromJSONTyped(json, false);
}

export function SortSortFieldFromJSONTyped(json: any, ignoreDiscriminator: boolean): SortSortField {
    return json as SortSortField;
}

export function SortSortFieldToJSON(value?: SortSortField | null): any {
    return value as any;
}

