/**
 * CDP Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CustomerUnsubscribeResponse {
    'response'?: boolean;
    'subscriberExist'?: boolean;
    'activeNewsletterGrn'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "response",
            "baseName": "response",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "subscriberExist",
            "baseName": "subscriberExist",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "activeNewsletterGrn",
            "baseName": "activeNewsletterGrn",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CustomerUnsubscribeResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

