/**
 * CDP Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CustomerAddressEntity } from '../models/CustomerAddressEntity';
import { CustomerEMFields } from '../models/CustomerEMFields';
import { CustomerNewsletterRequest } from '../models/CustomerNewsletterRequest';
import { CustomerPassword } from '../models/CustomerPassword';
import { ProtobufAny } from '../models/ProtobufAny';
import { HttpFile } from '../http/http';

export class CustomerUpdateRequestPayload {
    'em'?: CustomerEMFields;
    'name'?: string;
    'surname'?: string;
    'email'?: string;
    'birthdate'?: Date;
    'gender'?: string;
    'enabled'?: boolean;
    'source'?: string;
    'addresses'?: Array<CustomerAddressEntity>;
    'defaultBillingAddressId'?: string;
    'defaultShippingAddressId'?: string;
    'phoneNumber'?: string;
    'nationality'?: string;
    'groups'?: Array<string>;
    'deleted'?: boolean;
    'newsletters'?: Array<CustomerNewsletterRequest>;
    'attributes'?: { [key: string]: ProtobufAny; };
    'migratedPassword'?: CustomerPassword;
    'preferredLocale'?: string;
    'taxCode'?: string;
    'certifiedEmail'?: string;
    'market'?: string;
    'externalIds'?: { [key: string]: string; };

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "em",
            "baseName": "em",
            "type": "CustomerEMFields",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "surname",
            "baseName": "surname",
            "type": "string",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "birthdate",
            "baseName": "birthdate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "gender",
            "baseName": "gender",
            "type": "string",
            "format": ""
        },
        {
            "name": "enabled",
            "baseName": "enabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "source",
            "baseName": "source",
            "type": "string",
            "format": ""
        },
        {
            "name": "addresses",
            "baseName": "addresses",
            "type": "Array<CustomerAddressEntity>",
            "format": ""
        },
        {
            "name": "defaultBillingAddressId",
            "baseName": "defaultBillingAddressId",
            "type": "string",
            "format": ""
        },
        {
            "name": "defaultShippingAddressId",
            "baseName": "defaultShippingAddressId",
            "type": "string",
            "format": ""
        },
        {
            "name": "phoneNumber",
            "baseName": "phoneNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "nationality",
            "baseName": "nationality",
            "type": "string",
            "format": ""
        },
        {
            "name": "groups",
            "baseName": "groups",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "deleted",
            "baseName": "deleted",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "newsletters",
            "baseName": "newsletters",
            "type": "Array<CustomerNewsletterRequest>",
            "format": ""
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "{ [key: string]: ProtobufAny; }",
            "format": ""
        },
        {
            "name": "migratedPassword",
            "baseName": "migratedPassword",
            "type": "CustomerPassword",
            "format": ""
        },
        {
            "name": "preferredLocale",
            "baseName": "preferredLocale",
            "type": "string",
            "format": ""
        },
        {
            "name": "taxCode",
            "baseName": "taxCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "certifiedEmail",
            "baseName": "certifiedEmail",
            "type": "string",
            "format": ""
        },
        {
            "name": "market",
            "baseName": "market",
            "type": "string",
            "format": ""
        },
        {
            "name": "externalIds",
            "baseName": "externalIds",
            "type": "{ [key: string]: string; }",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CustomerUpdateRequestPayload.attributeTypeMap;
    }

    public constructor() {
    }
}

