/**
 * CDP Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CustomerSubscriberRequest } from '../models/CustomerSubscriberRequest';
import { HttpFile } from '../http/http';

export class CustomerCreateSubscriberRequest {
    'tenantId'?: string;
    'subscriber'?: CustomerSubscriberRequest;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "tenantId",
            "baseName": "tenantId",
            "type": "string",
            "format": ""
        },
        {
            "name": "subscriber",
            "baseName": "subscriber",
            "type": "CustomerSubscriberRequest",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CustomerCreateSubscriberRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

