/**
 * CDP Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CustomerEMFields } from '../models/CustomerEMFields';
import { CustomerNewsletterRequest } from '../models/CustomerNewsletterRequest';
import { HttpFile } from '../http/http';

export class CustomerSubscriberResponseWithNewsletterRequest {
    'id'?: string;
    'name'?: string;
    'lastname'?: string;
    'email'?: string;
    'country'?: string;
    'gender'?: string;
    'birthdate'?: Date;
    'nationality'?: string;
    'em'?: CustomerEMFields;
    'preferredLocale'?: string;
    'createdAt'?: Date;
    'updatedAt'?: Date;
    'newsletters'?: Array<CustomerNewsletterRequest>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastname",
            "baseName": "lastname",
            "type": "string",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "country",
            "baseName": "country",
            "type": "string",
            "format": ""
        },
        {
            "name": "gender",
            "baseName": "gender",
            "type": "string",
            "format": ""
        },
        {
            "name": "birthdate",
            "baseName": "birthdate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "nationality",
            "baseName": "nationality",
            "type": "string",
            "format": ""
        },
        {
            "name": "em",
            "baseName": "em",
            "type": "CustomerEMFields",
            "format": ""
        },
        {
            "name": "preferredLocale",
            "baseName": "preferredLocale",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "newsletters",
            "baseName": "newsletters",
            "type": "Array<CustomerNewsletterRequest>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CustomerSubscriberResponseWithNewsletterRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

