/**
 * CDP Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export enum CustomerConsentSource {
    Unknown = 'CONSENT_SOURCE_UNKNOWN',
    Frontend = 'CONSENT_SOURCE_FRONTEND',
    Backoffice = 'CONSENT_SOURCE_BACKOFFICE',
    Backend = 'CONSENT_SOURCE_BACKEND'
}
