/**
 * CDP Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PasswordPasswordType } from '../models/PasswordPasswordType';
import { HttpFile } from '../http/http';

export class CustomerPassword {
    'data'?: { [key: string]: string; };
    'enabled'?: boolean;
    'type'?: PasswordPasswordType;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "enabled",
            "baseName": "enabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "PasswordPasswordType",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CustomerPassword.attributeTypeMap;
    }

    public constructor() {
    }
}



