/**
 * CDP Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CustomerConsentSource } from '../models/CustomerConsentSource';
import { HttpFile } from '../http/http';

export class CustomerConsent {
    'id'?: string;
    'grn'?: string;
    'preferences'?: { [key: string]: boolean; };
    'createdAt'?: Date;
    'source'?: CustomerConsentSource;
    'author'?: string;
    'subjectId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "grn",
            "baseName": "grn",
            "type": "string",
            "format": ""
        },
        {
            "name": "preferences",
            "baseName": "preferences",
            "type": "{ [key: string]: boolean; }",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "source",
            "baseName": "source",
            "type": "CustomerConsentSource",
            "format": ""
        },
        {
            "name": "author",
            "baseName": "author",
            "type": "string",
            "format": ""
        },
        {
            "name": "subjectId",
            "baseName": "subjectId",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CustomerConsent.attributeTypeMap;
    }

    public constructor() {
    }
}



