/**
 * CDP Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CustomerCustomerResponse } from '../models/CustomerCustomerResponse';
import { HttpFile } from '../http/http';

export class CustomerFindManyResponse {
    'customers'?: Array<CustomerCustomerResponse>;
    'nextPageToken'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "customers",
            "baseName": "customers",
            "type": "Array<CustomerCustomerResponse>",
            "format": ""
        },
        {
            "name": "nextPageToken",
            "baseName": "nextPageToken",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CustomerFindManyResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

