/**
 * CDP Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export enum PasswordPasswordType {
    Unknown = 'PASSWORD_TYPE_UNKNOWN',
    Magento1 = 'PASSWORD_TYPE_MAGENTO1',
    Sylius = 'PASSWORD_TYPE_SYLIUS',
    Magento2 = 'PASSWORD_TYPE_MAGENTO2'
}
